# Generated by Django 4.2.6 on 2023-10-07 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('ingredients', models.TextField(blank=True, verbose_name='Інгредієнти')),
                ('complexity', models.CharField(choices=[('Легко', 'Легко'), ('Середня', 'Середня'), ('Складно', 'Складно')], max_length=200, verbose_name='Складність')),
                ('preparation_time', models.TimeField(blank=True, verbose_name='Час підготовки')),
                ('cooking_time', models.TimeField(blank=True, verbose_name='Час приготування')),
                ('image', models.ImageField(upload_to='images', verbose_name='Фото страви')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата і час створення')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата і час оновлення')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes_project.category', verbose_name='Категорія')),
            ],
        ),
    ]
