# Generated by Django 4.2.6 on 2023-10-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='recipes',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепти'},
        ),
        migrations.AddField(
            model_name='recipes',
            name='instructions_cooking',
            field=models.TextField(blank=True, verbose_name='Інструкція приготування'),
        ),
    ]
