# Generated by Django 4.2.6 on 2023-10-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_project', '0002_alter_category_options_alter_recipes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='category'),
        ),
    ]
