# Generated by Django 4.2.6 on 2023-12-02 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_project', '0006_recipes_slug_alter_recipes_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ['-published'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепти'},
        ),
        migrations.RemoveIndex(
            model_name='recipes',
            name='recipes_pro_create__953b94_idx',
        ),
        migrations.AddField(
            model_name='recipes',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 16, 59, 9, 599931, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='complexity',
            field=models.CharField(choices=[('Easy', 'Легко'), ('Aver', 'Середня'), ('Diff', 'Складно')], max_length=200, verbose_name='Складність'),
        ),
        migrations.AddIndex(
            model_name='recipes',
            index=models.Index(fields=['-published'], name='recipes_pro_publish_8627f8_idx'),
        ),
    ]
