# Generated by Django 4.2.6 on 2023-12-03 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_project', '0007_alter_recipes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 10, 41, 33, 442625, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='slug',
            field=models.CharField(max_length=120, unique_for_date='published'),
        ),
    ]
