# Generated by Django 4.2.6 on 2023-12-04 12:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_project', '0010_alter_recipes_complexity_alter_recipes_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 12, 36, 4, 665441, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipes_project.recipes')),
            ],
            options={
                'ordering': ['created'],
                'indexes': [models.Index(fields=['created'], name='recipes_pro_created_624f9f_idx')],
            },
        ),
    ]
