# Generated by Django 4.2.6 on 2024-02-23 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_project', '0012_alter_comments_options_alter_comments_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 10, 12, 36, 726431, tzinfo=datetime.timezone.utc)),
        ),
    ]
