# Generated by Django 4.2.6 on 2024-02-26 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes_project", "0013_alter_recipes_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipes",
            name="published",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 26, 14, 43, 42, 319049, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
